<?php

namespace App\Http\Requests\SuperAdmin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * T-133 (20-09-2026) — reassigning a store's owner is a protected action: the Super Admin must re-enter their own
 * account password with every reassignment (`current_password`). The new owner's Store Login password is always
 * auto-generated by the controller (T-117's force-reset rule stays), so this request carries no password fields for it.
 */
class ReassignStoreOwnerRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    /** @return array<string, mixed> */
    public function rules(): array
    {
        return [
            'owner_user_id' => ['required', 'integer', 'exists:users,id'],
            'current_password' => ['required', 'string', 'current_password'],
        ];
    }
}
